INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);
INSERT INTO users (name, age) VALUES ("Apples", 23);

INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 1", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 1", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 3", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 5", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 1", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 1", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 6", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 8", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 9", "movies", 23, 9, 10);
INSERT INTO projects (title, category, goal, start, end) VALUES ("Project 10", "movies", 23, 9, 10);

INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (4, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (6, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (7, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (4, 21, 4);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 4);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 9);
INSERT INTO pledges (user, amount, project) VALUES (9, 21, 9);
INSERT INTO pledges (user, amount, project) VALUES (3, 21, 4);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (2, 21, 3);
INSERT INTO pledges (user, amount, project) VALUES (2, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);
INSERT INTO pledges (user, amount, project) VALUES (5, 21, 7);


